### ISSUE TITLE
Detect Terraform binary in path

### ISSUE THREAD

**Issue by jsirianni** [RoseSecurity/Terramaid#12]
**Is your feature request related to a problem? Please describe.**

It would be nice if the Terraform binary was detected in the user's $PATH instead of defaulting to /usr/local/bin/terraform.

**Describe the solution you'd like**

Use exec.LookPath similar to the suggestion here https://stackoverflow.com/questions/46236173/find-binarys-in-path

**Describe alternatives you've considered**

I moved my Terraform binary from /usr/bin to /usr/local/bin to avoid using the flag.

**Additional context**

Just a quality of life improvement.

**Comment by RoseSecurity** [comment]
Great recommendation! I'll work on adding this into the next release!

**Comment by RoseSecurity** [comment]
Just created a [release](https://github.com/RoseSecurity/Terramaid/releases/tag/v1.4.0) with this recommendation! Thank you!
