### ISSUE TITLE
Unable to pull image locally, manifest unknown

### ISSUE THREAD

**Issue by guicane** [RoseSecurity/Terramaid#14]
**Describe the bug**
Unable to pull image locally, manifest unknown

**To Reproduce**
docker run -it -v $(pwd):/usr/src/terramaid rosesecurity/terramaid:latest   

Unable to find image 'rosesecurity/terramaid:latest' locally
docker: Error response from daemon: manifest for rosesecurity/terramaid:latest not found: manifest unknown: manifest unknown.

**Expected behavior**
Image is pulled

**Comment by xip-niekneuij** [comment]
Also not working on my kompjoeter

> go install github.com/rosesecurity/terramaid/v1@latest

```shell
go: downloading github.com/rosesecurity/terramaid v1.4.0
go: github.com/rosesecurity/terramaid/v1@latest: module github.com/rosesecurity/terramaid@latest found (v1.4.0), but does not contain package github.com/rosesecurity/terramaid/v1
```

**Comment by RoseSecurity** [comment]
Hey! Just added a GitHub action to publish to Docker Hub on each release, so feel free to give it a test! I also updated the documentation for the Go install which should resolve the issue! Thanks for reporting this!
