### ISSUE TITLE
Add Homebrew installation option

### ISSUE THREAD

**Issue by yermulnik** [RoseSecurity/Terramaid#17]
**Is your feature request related to a problem? Please describe.**
Homebrew is a popular macOS/Linux solution to manage packages, which is missing from `terramaid` yet.

**Describe the solution you'd like**
Add `terramaid` to [Core Homebrew repo](https://docs.brew.sh/Adding-Software-to-Homebrew) or maintain [Third-Party Tap](https://docs.brew.sh/Taps) (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap)

**Describe alternatives you've considered**
Provided installation options (go install, build from source and docker image) are missing features of package manager.

**Comment by yermulnik** [comment]
It also looks like Go installation method doesn't work out of the box 🤔 
```shell
> echo $GOPATH
/home/giermulnik/go

> go install github.com/rosesecurity/terramaid/v1@latest
go: downloading github.com/rosesecurity/terramaid v1.4.0
go: github.com/rosesecurity/terramaid/v1@latest: module github.com/rosesecurity/terramaid@latest found (v1.4.0), but does not contain package github.com/rosesecurity/terramaid/v1
```

**Comment by RoseSecurity** [comment]
I apologize for the documentation error, but I just updated it to reflect this and am working on getting it into Homebrew over the weekend! Here is the updated Go installation command:

```sh
go install github.com/RoseSecurity/terramaid@latest
```

**Comment by chenrui333** [comment]
@RoseSecurity I have filed [a PR](https://github.com/Homebrew/homebrew-core/pull/177862) to help include this project into core, can you take a look at this #24 to fix the version issue? Thanks!

**Comment by RoseSecurity** [comment]
> @RoseSecurity I have filed [a PR](https://github.com/Homebrew/homebrew-core/pull/177862) to help include this project into core, can you take a look at this #24 to fix the version issue? Thanks!

This looks great! Thank you for the contribution!

**Comment by RoseSecurity** [comment]
Thanks to @chenrui333, this issue is complete! Enjoy the easy installation!

```sh
brew install terramaid
```

More features coming soon!

**Comment by yermulnik** [comment]
🥳 Yay, appreciate all the effort. Yesterday already brew-installed `terramaid` and that worked fine 👍🏻
