### ISSUE TITLE
Support for Terragrunt

### ISSUE THREAD

**Issue by sirantd** [RoseSecurity/Terramaid#27]
Not sure if it's possible to implement but would be nice to support the Terragrunt

**Comment by RoseSecurity** [comment]
Thank you for expressing interest in our tooling!

At this time, we do not have plans to support Terragrunt in our roadmap. Our current focus is on enhancing and expanding our support for Terraform and OpenTofu. We appreciate your understanding and are always open to feedback and suggestions. If there are specific features or improvements you would like to see in our existing offerings, please feel free to share.
